### ISSUE TITLE
Question about custom HTML

### ISSUE THREAD

**Issue by ajboni** [Billiam/itchpack#1]
Hello!!
I found this repo trying to figure out how did you do the awesome deepdwn itch page.
This library seems perfect!! 
The only thing I cannot find info is where/how do you upload custom html/css to itch? 
I only [found this](https://itch.io/docs/creators/css-guide) but I think its something else...

Thanks!!

**Comment by Billiam** [comment]
You can paste your custom HTML into the description field on your itch page. There's a `<>` button in the toolbar to change the field to HTML

For the custom CSS, that's the right link so it's worth reading. You'll need to request access to custom CSS from itch.io's support, and then you can paste custom CSS into the 'custom css' field when you edit your page's theme.

Good luck!

**Comment by ajboni** [comment]
Oh for. A moment I though you could just upload those custom files hehe. Thanks for replying!
